"""add quantity_reserved to products

Revision ID: 1ac7349bb5fb
Revises: 55f19ad7737c
Create Date: 2026-07-10 07:02:47.141098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac7349bb5fb'
down_revision: Union[str, Sequence[str], None] = '55f19ad7737c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity_reserved', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity_reserved')
    # ### end Alembic commands ###
