"""add mono models + farmer bank/payout

Revision ID: aa4abbeda401
Revises: bf8b8753c7f1
Create Date: 2026-07-10 11:23:08.103542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4abbeda401'
down_revision: Union[str, Sequence[str], None] = 'bf8b8753c7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_bank_accounts_farmer_id'), 'farmer_bank_accounts', ['farmer_id'], unique=False)
    op.create_table('farmer_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('farmer_bank_account_id', sa.Integer(), nullable=True),
    sa.Column('mono_transfer_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_bank_account_id'], ['farmer_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_payouts_farmer_id'), 'farmer_payouts', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farmer_payouts_order_id'), 'farmer_payouts', ['order_id'], unique=False)
    op.add_column('payments', sa.Column('mono_intent_id', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('mono_transfer_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_payments_mono_intent_id'), 'payments', ['mono_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_mono_intent_id'), table_name='payments')
    op.drop_column('payments', 'mono_transfer_id')
    op.drop_column('payments', 'mono_intent_id')
    op.drop_index(op.f('ix_farmer_payouts_order_id'), table_name='farmer_payouts')
    op.drop_index(op.f('ix_farmer_payouts_farmer_id'), table_name='farmer_payouts')
    op.drop_table('farmer_payouts')
    op.drop_index(op.f('ix_farmer_bank_accounts_farmer_id'), table_name='farmer_bank_accounts')
    op.drop_table('farmer_bank_accounts')
    # ### end Alembic commands ###
